{
 "title": "SCOM Event Log",
 "description": "Event log viewer for investigating server events from the SCOM Data Warehouse. Filter by server and event level to narrow down root cause.",
 "tags": [
  "scom",
  "events",
  "troubleshooting"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "SELECT DISTINCT LEFT(STUFF(me.DisplayName, 1, 3, ''), CHARINDEX('-', STUFF(me.DisplayName, 1, 3, '')) - 1) AS __text, LEFT(STUFF(me.DisplayName, 1, 3, ''), CHARINDEX('-', STUFF(me.DisplayName, 1, 3, '')) - 1) AS __value FROM vManagedEntity me WHERE me.ManagedEntityTypeRowId = 1 AND me.DisplayName LIKE 'VM-%' ORDER BY 1"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SELECT DISTINCT me.DisplayName AS __text, me.DisplayName AS __value FROM vManagedEntity me WHERE me.ManagedEntityTypeRowId = 1 AND me.DisplayName LIKE 'VM-${site:raw}-%' ORDER BY me.DisplayName"
   },
   { "name": "event_level", "label": "Event Level", "query": "All,Error,Warning,Information" }
  ]
 },
 "panels": [
  { "title": "Event Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Errors\"\nFROM Event.vEvent e\nINNER JOIN dbo.vEventLevel el ON e.EventLevelId = el.EventLevelId\nINNER JOIN dbo.vEventLoggingComputer elc ON e.LoggingComputerRowId = elc.LoggingComputerRowId\nWHERE el.EventLevelName = 'Error'\nAND elc.LoggingComputerName = '${server:raw}'\nAND $__timeFilter(e.DateTime)"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Warnings\"\nFROM Event.vEvent e\nINNER JOIN dbo.vEventLevel el ON e.EventLevelId = el.EventLevelId\nINNER JOIN dbo.vEventLoggingComputer elc ON e.LoggingComputerRowId = elc.LoggingComputerRowId\nWHERE el.EventLevelName = 'Warning'\nAND elc.LoggingComputerName = '${server:raw}'\nAND $__timeFilter(e.DateTime)"
    }
   ]
  },
  {
   "title": "Info Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Information\"\nFROM Event.vEvent e\nINNER JOIN dbo.vEventLevel el ON e.EventLevelId = el.EventLevelId\nINNER JOIN dbo.vEventLoggingComputer elc ON e.LoggingComputerRowId = elc.LoggingComputerRowId\nWHERE el.EventLevelName = 'Information'\nAND elc.LoggingComputerName = '${server:raw}'\nAND $__timeFilter(e.DateTime)"
    }
   ]
  },
  { "title": "Event Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Events Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATEADD(hour, DATEDIFF(hour, 0, e.DateTime), 0) AS time,\n  el.EventLevelName AS metric,\n  COUNT(*) AS value\nFROM Event.vEvent e\nINNER JOIN dbo.vEventLevel el ON e.EventLevelId = el.EventLevelId\nINNER JOIN dbo.vEventLoggingComputer elc ON e.LoggingComputerRowId = elc.LoggingComputerRowId\nWHERE elc.LoggingComputerName = '${server:raw}'\nAND ('${event_level:raw}' = 'All' OR el.EventLevelName = '${event_level:raw}')\nAND $__timeFilter(e.DateTime)\nGROUP BY DATEADD(hour, DATEDIFF(hour, 0, e.DateTime), 0), el.EventLevelName\nORDER BY time"
    }
   ]
  },
  { "title": "Event Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Event Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT TOP 200\n  e.DateTime AS \"Time\",\n  el.EventLevelName AS \"Level\",\n  ep.EventPublisherName AS \"Source\",\n  ec.EventChannelName AS \"Channel\",\n  e.EventDisplayNumber AS \"Event ID\",\n  e.RawDescription AS \"Description\"\nFROM Event.vEvent e\nINNER JOIN dbo.vEventPublisher ep ON e.EventPublisherRowId = ep.EventPublisherRowId\nINNER JOIN dbo.vEventChannel ec ON e.EventChannelRowId = ec.EventChannelRowId\nINNER JOIN dbo.vEventLevel el ON e.EventLevelId = el.EventLevelId\nINNER JOIN dbo.vEventLoggingComputer elc ON e.LoggingComputerRowId = elc.LoggingComputerRowId\nWHERE elc.LoggingComputerName = '${server:raw}'\nAND ('${event_level:raw}' = 'All' OR el.EventLevelName = '${event_level:raw}')\nAND $__timeFilter(e.DateTime)\nORDER BY e.DateTime DESC"
    }
   ]
  }
 ]
}